# =============================================================================
# routers/greek_grid.py  —  mounted at /greek-grid
# =============================================================================
# Natural-language interpretation of the Greek grid: turns a strike × DTE
# matrix of dealer-positioning Greeks into readable analysis for the UI.
#
#   POST /greek-grid/interpret-grid   a grid snapshot  -> cross-sectional read
#   POST /greek-grid/interpret-chart  one bucket's history -> read over time
#
# Logic: api/services/greek_interpreter.py
# Data:  written by api/jobs/greek_grid_pull.py + services/greek_grid_ingester.py
# UI:    lib/features/greek_grid/
#
# These endpoints are pure interpretation — they compute no Greeks. The grid is
# already built and stored; this layer reads it and explains what the
# positioning implies (where dealers are long or short gamma, which strikes pin,
# where the regime flips). It lives in Python rather than Dart so the wording
# and thresholds are versioned with the analytics that produced the numbers.
#
# The two endpoints are deliberately different cuts of the same data:
#   interpret-grid   ACROSS strikes and DTEs at one instant — "where is the
#                    risk concentrated right now?"
#   interpret-chart  ALONG time within a single DTE bucket — "how has that
#                    concentration been building?"
#
# Response shape is whatever the service returns (untyped dict), so wording and
# fields can evolve without a schema change here. The Flutter side reads keys
# defensively for that reason.
# =============================================================================

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Any

from services.greek_interpreter import interpret_greek_grid, interpret_greek_chart

router = APIRouter()


# ── Interpretation ─────────────────────────────────────────────────────────────

class InterpretGridRequest(BaseModel):
    # Loosely typed on purpose: the cells are forwarded straight from the
    # greek_grid table rows, and the interpreter reads the keys it needs.
    # Adding a Greek to the grid therefore needs no change in this file.
    grid_cells: list[dict[str, Any]]


class InterpretChartRequest(BaseModel):
    chart_history: list[dict[str, Any]]
    # Which DTE bucket the history belongs to. Passed separately because the
    # interpretation is bucket-dependent: near-dated gamma pins price, while the
    # same reading 90 days out says something much weaker.
    dte_bucket: int


@router.post("/interpret-grid")
def greek_grid_interpret_grid(req: InterpretGridRequest):
    """Interpret a Greek grid snapshot across strikes and DTEs.

    The broad try/except converts ANY service failure into a 500 carrying the
    exception text. That includes failures caused by malformed input, which
    arguably deserve a 4xx — but the grid cells are machine-generated by our own
    ingester rather than hand-built by a user, so a malformed cell really does
    indicate a server-side problem worth surfacing as one.

    Catching here rather than relying on main.py's global handler keeps the
    detail message specific to this call. Both paths set CORS headers, so the
    browser sees the error either way.
    """
    try:
        return interpret_greek_grid(req.grid_cells)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/interpret-chart")
def greek_grid_interpret_chart(req: InterpretChartRequest):
    """Interpret one DTE bucket's Greek history as a time series.

    Same error contract as interpret-grid above.
    """
    try:
        return interpret_greek_chart(req.chart_history, req.dte_bucket)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
